import {
  Folder,
  HelpCircle,
  Cpu,
  Code,
  Wifi,
  Printer,
  Mail,
  Shield,
  Phone,
  Monitor,
  Database,
  Server,
  Globe,
  Settings,
  Wrench,
  Package,
  Zap,
  Activity,
  MoreHorizontal,
  Bug,
  FileText,
  DollarSign,
  Lightbulb,
  AlertCircle,
  Users,
  Calendar,
  Clock,
  Search,
  Home,
  Star,
  Heart,
  Tag,
  Bookmark,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Volume2,
  Bell,
  BellOff,
  Lock,
  Unlock,
  Key,
  CreditCard,
  Gift,
  Award,
  Trophy,
  Target,
  Compass,
  Map,
  Navigation,
  Briefcase,
  ShoppingCart,
  ShoppingBag,
  Archive,
  Trash2,
  Edit,
  Copy,
  Clipboard,
  Download,
  Upload,
  Cloud,
  CloudOff,
  Sun,
  Moon,
  CloudRain,
  Umbrella,
  Coffee,
  Battery,
  BatteryCharging,
  Bluetooth,
  Cast,
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Radio,
  Layers,
  Layout,
  Grid,
  List,
  Maximize,
  Minimize,
  Move,
  PlusCircle,
  MinusCircle,
  XCircle,
  CheckCircle,
  AlertTriangle,
  Info,
  HelpCircle as QuestionCircle,
  Flag,
  Bookmark as Pin,
  Paperclip,
  Link,
  Anchor,
  Send,
  MessageSquare,
  MessageCircle,
  Share,
  ThumbsUp,
  ThumbsDown,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Users as Team,
  Eye,
  EyeOff,
  Filter,
  SlidersHorizontal,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign as Currency,
  Percent,
  Calculator,
  Clipboard as Board,
  BookOpen,
  Book,
  FileText as Document,
  File,
  FolderOpen,
  Save,
  RefreshCw,
  RotateCw,
  Loader,
  Power,
  Plug,
  Ticket,
  Tag as Label,
  Hash,
  AtSign,
  Chrome,
  Github,
  Gitlab,
  Slack,
  Trello,
  Figma,
} from 'lucide-react'
import { LucideIcon } from 'lucide-react'

// Mapeamento de nomes de ícones (string) para componentes
export const iconMap: Record<string, LucideIcon> = {
  // Categorias padrão
  'folder': Folder,
  'help-circle': HelpCircle,
  'cpu': Cpu,
  'code': Code,
  'wifi': Wifi,
  'printer': Printer,
  'mail': Mail,
  'shield': Shield,
  'phone': Phone,
  'monitor': Monitor,
  'database': Database,
  'server': Server,
  'globe': Globe,
  'settings': Settings,
  'tool': Wrench,
  'wrench': Wrench,
  'package': Package,
  'zap': Zap,
  'activity': Activity,
  'more-horizontal': MoreHorizontal,
  
  // Ícones adicionais úteis
  'bug': Bug,
  'file-text': FileText,
  'dollar-sign': DollarSign,
  'lightbulb': Lightbulb,
  'alert-circle': AlertCircle,
  'users': Users,
  'calendar': Calendar,
  'clock': Clock,
  'search': Search,
  'home': Home,
  'star': Star,
  'heart': Heart,
  'tag': Tag,
  'bookmark': Bookmark,
  'camera': Camera,
  'image': Image,
  'video': Video,
  'music': Music,
  'headphones': Headphones,
  'mic': Mic,
  'volume': Volume2,
  'bell': Bell,
  'bell-off': BellOff,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'credit-card': CreditCard,
  'gift': Gift,
  'award': Award,
  'trophy': Trophy,
  'target': Target,
  'compass': Compass,
  'map': Map,
  'navigation': Navigation,
  'briefcase': Briefcase,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'archive': Archive,
  'trash': Trash2,
  'edit': Edit,
  'copy': Copy,
  'clipboard': Clipboard,
  'download': Download,
  'upload': Upload,
  'cloud': Cloud,
  'cloud-off': CloudOff,
  'sun': Sun,
  'moon': Moon,
  'cloud-rain': CloudRain,
  'umbrella': Umbrella,
  'coffee': Coffee,
  'battery': Battery,
  'battery-charging': BatteryCharging,
  'bluetooth': Bluetooth,
  'cast': Cast,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'tv': Tv,
  'radio': Radio,
  'layers': Layers,
  'layout': Layout,
  'grid': Grid,
  'list': List,
  'maximize': Maximize,
  'minimize': Minimize,
  'move': Move,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  'x-circle': XCircle,
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle,
  'info': Info,
  'question-circle': QuestionCircle,
  'flag': Flag,
  'pin': Pin,
  'paperclip': Paperclip,
  'link': Link,
  'anchor': Anchor,
  'send': Send,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'share': Share,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  'team': Team,
  'eye': Eye,
  'eye-off': EyeOff,
  'filter': Filter,
  'sliders': SlidersHorizontal,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'currency': Currency,
  'percent': Percent,
  'calculator': Calculator,
  'board': Board,
  'book-open': BookOpen,
  'book': Book,
  'document': Document,
  'file': File,
  'folder-open': FolderOpen,
  'save': Save,
  'refresh': RefreshCw,
  'rotate': RotateCw,
  'loader': Loader,
  'power': Power,
  'plug': Plug,
  'ticket': Ticket,
  'label': Label,
  'hash': Hash,
  'at-sign': AtSign,
  'chrome': Chrome,
  'github': Github,
  'gitlab': Gitlab,
  'slack': Slack,
  'trello': Trello,
  'figma': Figma,
}

// Função helper para obter o ícone correto
export function getIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return Folder // Ícone padrão
  
  const icon = iconMap[iconName.toLowerCase()]
  return icon || Folder // Retorna Folder como fallback se o ícone não for encontrado
}