import {
  Folder,
  HelpCircle,
  Cpu,
  Code,
  Wifi,
  Printer,
  Mail,
  Shield,
  Phone,
  Monitor,
  Database,
  Server,
  Globe,
  Settings,
  Wrench,
  Package,
  Package2,
  PackageCheck,
  PackageX,
  PackageSearch,
  PackagePlus,
  PackageMinus,
  Boxes,
  Warehouse,
  Zap,
  Activity,
  MoreHorizontal,
  Bug,
  FileText,
  DollarSign,
  Lightbulb,
  AlertCircle,
  Users,
  User,
  Calendar,
  Clock,
  Search,
  Home,
  Star,
  Heart,
  Tag,
  Bookmark,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Volume2,
  Bell,
  BellOff,
  Lock,
  Unlock,
  Key,
  CreditCard,
  Gift,
  Award,
  Trophy,
  Target,
  Compass,
  Map,
  Navigation,
  Briefcase,
  ShoppingCart,
  ShoppingBag,
  Archive,
  Trash2,
  Edit,
  Copy,
  Clipboard,
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  Layers,
  LayoutGrid,
  Grid3x3,
  ScanLine,
  QrCode,
  Scan,
  Download,
  Upload,
  Cloud,
  CloudOff,
  Sun,
  Moon,
  CloudRain,
  Umbrella,
  Coffee,
  Battery,
  BatteryCharging,
  Bluetooth,
  Cast,
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Radio,
  Layout,
  Grid,
  List,
  Maximize,
  Minimize,
  Move,
  PlusCircle,
  MinusCircle,
  XCircle,
  CheckCircle,
  AlertTriangle,
  Info,
  HelpCircle as QuestionCircle,
  Flag,
  Bookmark as Pin,
  Paperclip,
  Link,
  Anchor,
  Send,
  MessageSquare,
  MessageCircle,
  Share,
  ThumbsUp,
  ThumbsDown,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Users as Team,
  Eye,
  EyeOff,
  Filter,
  SlidersHorizontal,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign as Currency,
  Percent,
  Calculator,
  Clipboard as Board,
  BookOpen,
  Book,
  FileText as Document,
  File,
  FolderOpen,
  Save,
  RefreshCw,
  RotateCw,
  Loader,
  Power,
  Plug,
  Ticket,
  Tag as Label,
  Hash,
  AtSign,
  Chrome,
  Github,
  Gitlab,
  Slack,
  Trello,
  Figma,
  Truck,
  Box,
  Container,
  Plane,
  Ship,
  Car,
  Bike,
  Route,
  MapPin,
  // Expansão completa de ícones por domínio
  Store,
  BarChart3,
  Terminal,
  GitBranch,
  FileTransfer,
  HardDrive,
  Disc,
  Building,
  // E-commerce & Vendas
  BadgeDollarSign,
  Receipt,
  Wallet,
  CreditCard as Card,
  Banknote,
  ShoppingBag as Bag,
  Package as Box2,
  Gift as Present,
  Percent as Discount,
  // Logistics & Transport
  Forklift,
  Containers,
  PlaneTakeoff,
  ShipWheel,
  CarFront,
  BusFront,
  Train,
  MapPin as Location,
  Route as Path,
  Navigation as GPS,
  // Technology & IT
  HardDrive as Storage,
  Disc as DVD,
  Cpu as Processor,
  MemoryStick,
  Router,
  Cable,
  Ethernet,
  MousePointer,
  Keyboard,
  // Development
  FileCode,
  Braces,
  CommandIcon,
  PackageOpen,
  FileJson,
  FileX,
  Merge,
  PullRequest,
  // Database & Analytics
  TableProperties,
  BarChart2,
  LineChart,
  Gauge,
  CircuitBoard,
  Binary,
  DatabaseZap,
  // Help & Support
  Headset,
  MessageCircle as Chat,
  Phone as PhoneCall,
  PhoneOutgoing,
  PhoneIncoming,
  LifeBuoy,
  UserRound,
  Users2,
  // Warehouse & Inventory
  Package2 as Parcel,
  PackageOpen as OpenBox,
  Boxes as MultipleBoxes,
  ArchiveRestore,
  Clipboard as Checklist,
  ClipboardPen,
  ScanBarcode,
  QrCodeIcon
} from 'lucide-react'
import { LucideIcon } from 'lucide-react'

// Mapeamento de nomes de ícones (string) para componentes
export const iconMap: Record<string, LucideIcon> = {
  // Categorias padrão
  'folder': Folder,
  'help-circle': HelpCircle,
  'cpu': Cpu,
  'code': Code,
  'wifi': Wifi,
  'printer': Printer,
  'mail': Mail,
  'shield': Shield,
  'phone': Phone,
  'monitor': Monitor,
  'database': Database,
  'server': Server,
  'globe': Globe,
  'settings': Settings,
  'tool': Wrench,
  'wrench': Wrench,
  'package': Package,
  'zap': Zap,
  'activity': Activity,
  'more-horizontal': MoreHorizontal,
  
  // WMS - Warehouse Management System
  'warehouse': Warehouse,
  'package-2': Package2,
  'package-check': PackageCheck,
  'package-x': PackageX,
  'package-search': PackageSearch,
  'package-plus': PackagePlus,
  'package-minus': PackageMinus,
  'boxes': Boxes,
  'barcode': ScanLine,
  'qr-code': QrCode,
  'scan': Scan,
  
  // Logística e Transporte
  'truck': Truck,
  'box': Box,
  'container': Container,
  'plane': Plane,
  'ship': Ship,
  'car': Car,
  'bike': Bike,
  'route': Route,
  'map-pin': MapPin,
  
  // Inventário
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  'layers': Layers,
  'layout-grid': LayoutGrid,
  'grid-3x3': Grid3x3,
  
  // Ícones adicionais úteis
  'bug': Bug,
  'file-text': FileText,
  'dollar-sign': DollarSign,
  'lightbulb': Lightbulb,
  'alert-circle': AlertCircle,
  'users': Users,
  'user': User,
  'calendar': Calendar,
  'clock': Clock,
  'search': Search,
  'home': Home,
  'star': Star,
  'heart': Heart,
  'tag': Tag,
  'bookmark': Bookmark,
  'camera': Camera,
  'image': Image,
  'video': Video,
  'music': Music,
  'headphones': Headphones,
  'mic': Mic,
  'volume': Volume2,
  'bell': Bell,
  'bell-off': BellOff,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'credit-card': CreditCard,
  'gift': Gift,
  'award': Award,
  'trophy': Trophy,
  'target': Target,
  'compass': Compass,
  'map': Map,
  'navigation': Navigation,
  'briefcase': Briefcase,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'archive': Archive,
  'trash': Trash2,
  'edit': Edit,
  'copy': Copy,
  'clipboard': Clipboard,
  'download': Download,
  'upload': Upload,
  'cloud': Cloud,
  'cloud-off': CloudOff,
  'sun': Sun,
  'moon': Moon,
  'cloud-rain': CloudRain,
  'umbrella': Umbrella,
  'coffee': Coffee,
  'battery': Battery,
  'battery-charging': BatteryCharging,
  'bluetooth': Bluetooth,
  'cast': Cast,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'tv': Tv,
  'radio': Radio,
  'layout': Layout,
  'grid': Grid,
  'list': List,
  'maximize': Maximize,
  'minimize': Minimize,
  'move': Move,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  'x-circle': XCircle,
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle,
  'info': Info,
  'question-circle': QuestionCircle,
  'flag': Flag,
  'pin': Pin,
  'paperclip': Paperclip,
  'link': Link,
  'anchor': Anchor,
  'send': Send,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'share': Share,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  'team': Team,
  'eye': Eye,
  'eye-off': EyeOff,
  'filter': Filter,
  'sliders': SlidersHorizontal,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'currency': Currency,
  'percent': Percent,
  'calculator': Calculator,
  'board': Board,
  'book-open': BookOpen,
  'book': Book,
  'document': Document,
  'file': File,
  'folder-open': FolderOpen,
  'save': Save,
  'refresh': RefreshCw,
  'rotate': RotateCw,
  'loader': Loader,
  'power': Power,
  'plug': Plug,
  'ticket': Ticket,
  'label': Label,
  'hash': Hash,
  'at-sign': AtSign,
  'chrome': Chrome,
  'github': Github,
  'gitlab': Gitlab,
  'slack': Slack,
  'trello': Trello,
  'figma': Figma,
  
  // E-COMMERCE & VENDAS
  'store': Store,
  'badge-dollar-sign': BadgeDollarSign,
  'receipt': Receipt,
  'wallet': Wallet,
  'card': Card,
  'banknote': Banknote,
  'bag': Bag,
  'present': Present,
  'discount': Discount,
  
  // LOGISTICS & TRANSPORT (TMS)
  'forklift': Forklift,
  'containers': Containers,
  'plane-takeoff': PlaneTakeoff,
  'ship-wheel': ShipWheel,
  'car-front': CarFront,
  'bus-front': BusFront,
  'train': Train,
  'location': Location,
  'path': Path,
  'gps': GPS,
  
  // TECHNOLOGY & IT
  'storage': Storage,
  'dvd': DVD,
  'processor': Processor,
  'memory-stick': MemoryStick,
  'router': Router,
  'cable': Cable,
  'ethernet': Ethernet,
  'mouse-pointer': MousePointer,
  'keyboard': Keyboard,
  
  // DEVELOPMENT
  'file-code': FileCode,
  'braces': Braces,
  'command': CommandIcon,
  'package-open': PackageOpen,
  'file-json': FileJson,
  'file-x': FileX,
  'merge': Merge,
  'pull-request': PullRequest,
  'git-branch': GitBranch,
  'terminal': Terminal,
  
  // DATABASE & ANALYTICS
  'table-properties': TableProperties,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'line-chart': LineChart,
  'gauge': Gauge,
  'circuit-board': CircuitBoard,
  'binary': Binary,
  'database-zap': DatabaseZap,
  'hard-drive': HardDrive,
  'disc': Disc,
  
  // HELP DESK & SUPPORT
  'headset': Headset,
  'chat': Chat,
  'phone-call': PhoneCall,
  'phone-outgoing': PhoneOutgoing,
  'phone-incoming': PhoneIncoming,
  'life-buoy': LifeBuoy,
  'user-round': UserRound,
  'users-2': Users2,
  
  // WAREHOUSE & INVENTORY (WMS)
  'parcel': Parcel,
  'open-box': OpenBox,
  'multiple-boxes': MultipleBoxes,
  'archive-restore': ArchiveRestore,
  'checklist': Checklist,
  'clipboard-pen': ClipboardPen,
  'scan-barcode': ScanBarcode,
  'qr-code-icon': QrCodeIcon,
  
  // FTP & FILE TRANSFER
  'file-transfer': FileTransfer,
  'building': Building,
}

// Função helper para obter o ícone correto
export function getIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return Folder // Ícone padrão
  
  const icon = iconMap[iconName.toLowerCase()]
  return icon || Folder // Retorna Folder como fallback se o ícone não for encontrado
}